export default {
    CONNECT: 'ws/CONNECT',
    CONNECT_SUCC: 'ws/CONNECT_SUCC',
    UPDATE_PROFIBILITY: 'ws/UPDATE_PROFIBILITY',
    UPDATE_SYSTEM_STATUS: 'ws/UPDATE_SYSTEM_STATUS',
    UPDATE_HASHRATE: 'ws/UPDATE_HASHRATE',
    RECENT_BLOCK: 'ws/RECENT_BLOCK',
    UPDATE_BALANCE: 'WS/UPDATE_BALANCE',
};
