export default {
    FETCH_IMG: 'api/FETCH_IMG',
    FETCH_IMG_SUCC: 'api/FETCH_IMG_SUCC',
    FETCH_IMG_FAILED: 'api/FETCH_IMG_FAILED',
    FETCH_POOL_DEBT: 'api/FETCH_POOL_DEBT',
    FETCH_POOL_DEBT_SUCC: 'api/FETCH_POOL_DEBT_SUCC',
    FETCH_POOL_DEBT_FAILED: 'api/FETCH_POOL_DEBT_FAILED',
    FETCH_REPORT: 'api/FETCH_REPORT',
    FETCH_REPORT_SUCC: 'api/FETCH_REPORT_SUCC',
    FETCH_REPORT_FAILED: 'api/FETCH_REPORT_FAILED',
};
